# Generated by Django 6.0.2 on 2026-03-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalsystem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=120),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtest', to='hospitalsystem.appointement'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalrecord', to='hospitalsystem.appointement'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='hospitalsystem.appointement'),
        ),
    ]
