# Generated by Django 6.0.2 on 2026-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('doctor', 'doctor'), ('patient', 'patient')], default=None, max_length=50, null=True),
        ),
    ]
