# Generated by Django 6.0.2 on 2026-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
