# Generated by Django 6.0.2 on 2026-03-09 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_bio_alter_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointement_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
