# Generated by Django 6.0.2 on 2026-03-09 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_next_available_appointement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointement_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
